source "https://rubygems.org"

gem 'fluentd', '>= 1.7.1'
gem 'fluent-plugin-record-reformer'
gem 'fluent-plugin-s3', '>= 1.2.0'
gem 'fluent-plugin-kinesis', '>= 3.2.0'
gem 'fluent-plugin-kafka', '>= 0.11.2'
gem 'fluent-plugin-elasticsearch', '>= 3.5.6'
gem 'fluent-plugin-scribe'
gem 'fluent-plugin-mongo', '>= 1.4.0'
gem 'fluent-plugin-webhdfs', '>= 1.2.5'
gem 'fluent-plugin-rewrite-tag-filter', '>= 2.3.0'
gem 'fluent-plugin-cloudwatch-logs', '>= 0.7.5'
