source "https://rubygems.org"

gem 'fluentd'
gem 'fluent-plugin-record-reformer'
gem 'fluent-plugin-s3'
gem 'fluent-plugin-kinesis'
gem 'fluent-plugin-kafka'
gem 'fluent-plugin-elasticsearch', '>= 3.5.6'
gem 'fluent-plugin-scribe'
gem 'fluent-plugin-mongo'
gem 'fluent-plugin-webhdfs'
gem 'fluent-plugin-rewrite-tag-filter'
gem 'fluent-plugin-cloudwatch-logs'
