source "https://rubygems.org"

gem 'fluentd'
gem 'fluent-plugin-record-reformer'
gem 'fluent-plugin-s3'
gem 'fluent-plugin-kinesis', '>= 3.1.0'
gem 'fluent-plugin-kafka'
gem 'fluent-plugin-elasticsearch'
gem 'fluent-plugin-scribe'
gem 'fluent-plugin-mongo'
gem 'fluent-plugin-webhdfs'
gem 'fluent-plugin-rewrite-tag-filter'
gem 'fluent-plugin-cloudwatch-logs'
