source "https://rubygems.org"

gem "jekyll", ">= 4.2.0"

gem "jekyll-avatar", ">= 0.8.0"
gem "jekyll-mentions"
gem "jekyll-seo-tag", ">= 2.7.0"
gem "jekyll-sitemap"
gem "jemoji", ">= 0.13.0"

# Optional dependencies:
gem "jekyll-coffeescript"
#gem "jekyll-docs"
gem "jekyll-feed", "~> 0.15", ">= 0.15.1"
gem "jekyll-gist"
gem "jekyll-paginate"
gem "jekyll-redirect-from"
gem "kramdown-syntax-coderay"
gem "mime-types", "~> 3.0"
gem "rdoc", "~> 6.0"
gem "tomlrb", "~> 1.2"

platform :ruby, :mswin, :mingw, :x64_mingw do
  gem "classifier-reborn", "~> 2.2"
  gem "liquid-c", "~> 4.0"
  gem "yajl-ruby", "~> 1.4"
end
